spring:
  datasource:
    url: jdbc:mysql://192.168.16.148:3306/mall?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    hikari:
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml